"""Environmental variables for Azure Functions"""

import os

STORAGE_TABLE_CONNECTOR_ACCESS_POINT = os.environ["STORAGE_TABLE_CONNECTOR_ACCESS_POINT"]
STORAGE_TABLE_CONNECTOR_API_KEY = os.environ["STORAGE_TABLE_CONNECTOR_API_KEY"]
SERVICEBUS_CONNECTION_STRING = os.environ["SERVICEBUS_CONNECTION_STRING"]
QUEUE_INTERNAL = os.environ["SERVICEBUS_QUEUE_NIP_TO_CHECK"]
SERVICEBUS_APP_SETTING_NAME = "SERVICEBUS_CONNECTION_STRING"
LOGGER_LEVEL = os.environ["LOGGER_LEVEL"]
